<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../package.props" />

  <PropertyGroup>
    <TargetFrameworks>net10.0;net472</TargetFrameworks>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**\*</DefaultItemExcludes>
    <Description>The MSBuild logger for Buildalyzer. Not intended to be used directly.</Description>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);PackLogger</TargetsForTfmSpecificBuildOutput>
    <PackageId>Buildalyzer.Logger</PackageId>
    <PackageValidationBaselineVersion>6.0.0</PackageValidationBaselineVersion>
    <OutputType>library</OutputType>
    <PackageReleaseNotes>
      <![CDATA[
ToBeReleased
- Target .NET 8.0. #252
- Publish SBOM.
      ]]>
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="18.6.3" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.6.3" PrivateAssets="All" />
    <PackageReference Include="MsBuildPipeLogger.Logger" Version="1.1.6" PrivateAssets="All" IsLogger="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Sbom.Targets" Version="4.1.5" />
    <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>

  <!-- Get the logger files for later use -->
  <Target Name="GetLoggerFiles" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <LoggerFiles Include="$([MSBuild]::EnsureTrailingSlash($(NuGetPackageRoot)))msbuildpipelogger.logger/%(PackageReference.Version)/**/*.dll" />
    </ItemGroup>
    <Error Condition="'@(LoggerFiles)' == ''" Text="Could not find MsBuildPipeLogger.Logger files" />
  </Target>

  <!-- Workaround to pack package reference directly -->
  <!-- See https://github.com/NuGet/Home/issues/3891 -->
  <!-- And https://github.com/NuGet/Home/issues/4837 -->
  <Target Name="PackLogger" DependsOnTargets="GetLoggerFiles">
    <ItemGroup>
      <BuildOutputInPackage Include="@(LoggerFiles)" />
    </ItemGroup>
  </Target>

  <Target Name="GetLoggerRuntimeFiles" Returns="@(LoggerRuntimeFile)">
    <ItemGroup>
      <LoggerRuntimeFile Include="$(TargetDir)**\*.*">
        <TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
      </LoggerRuntimeFile>
    </ItemGroup>
  </Target>

</Project>
